#include "shared_ptr.h"

#include <atomic>
#include <cstdlib>
#include <iostream>
#include <memory>
#include <string>
#include <thread>
#include <vector>

/*
 * Note: This file was generated by Claude to test my shared_ptr implementation against the stdlib implementation.
 */

#define CHECK(c)                                                   \
    do                                                             \
    {                                                              \
        if (!(c))                                                  \
        {                                                          \
            std::cout << "FAIL line " << __LINE__ << ": " #c "\n"; \
            std::abort();                                          \
        }                                                          \
    } while (0)

// owns heap memory and counts live instances, so it catches shallow copies,
// double frees, and leaks under a sanitizer.
struct Heavy
{
    static int alive;
    std::string name;
    std::vector<int> buffer;
    Heavy(std::string n, int n_elems) : name(std::move(n)), buffer(n_elems, 7) { ++alive; }
    ~Heavy() { --alive; }
    int sum() const
    {
        int s = 0;
        for (int x : buffer)
            s += x;
        return s;
    }
};
int Heavy::alive = 0;

struct Base
{
    static int alive;
    Base() { ++alive; }
    virtual ~Base() { --alive; }
    virtual int tag() const { return 0; }
};
int Base::alive = 0;

struct Derived : Base
{
    int extra;
    Derived(int e) : extra(e) {}
    int tag() const override { return extra; }
};

struct Counted
{
    static std::atomic<int> alive;
    Counted() { alive.fetch_add(1); }
    ~Counted() { alive.fetch_sub(1); }
};
std::atomic<int> Counted::alive{0};

// Bridges the strong-count accessor: my pointer exposes refCount(), std exposes use_count().
// This lets one test body run against both implementations.
template <class T>
long count_of(const shared_ptr<T> &p) { return p.refCount(); }
template <class T>
long count_of(const std::shared_ptr<T> &p) { return p.use_count(); }

// The suite is templated on the pointer family (SP) and its weak counterpart (WP), so the
// identical assertions run against both my implementation and the standard library.
template <template <class> class SP, template <class> class WP>
void run_all(const char *impl)
{
    // 1. ownership, copy, dereference, shared semantics.
    {
        CHECK(Heavy::alive == 0);
        {
            SP<Heavy> a(new Heavy("config", 4));
            CHECK(Heavy::alive == 1);
            CHECK((*a).name == "config" && a->sum() == 28);
            SP<Heavy> b = a;
            CHECK(Heavy::alive == 1);
            CHECK(count_of(a) == 2);
            b->buffer[0] = 100;
            CHECK(a->buffer[0] == 100);
        }
        CHECK(Heavy::alive == 0);
    }

    // 2. copy assignment releases the old owner before adopting the new one.
    {
        CHECK(Heavy::alive == 0);
        {
            SP<Heavy> a(new Heavy("first", 1));
            SP<Heavy> b(new Heavy("second", 1));
            CHECK(Heavy::alive == 2);
            a = b;
            CHECK(Heavy::alive == 1);
            CHECK(a->name == "second" && count_of(a) == 2);
        }
        CHECK(Heavy::alive == 0);
    }

    // 3. move semantics and safety of operating on a moved-from (empty) pointer.
    {
        CHECK(Heavy::alive == 0);
        {
            SP<Heavy> a(new Heavy("x", 2));
            SP<Heavy> b = std::move(a);
            CHECK(Heavy::alive == 1 && count_of(b) == 1);
            CHECK(count_of(a) == 0);
            SP<Heavy> c = a;
            CHECK(count_of(c) == 0 && Heavy::alive == 1);
            c = b;
            CHECK(count_of(c) == 2);
            b = std::move(c);
            CHECK(count_of(b) == 1 && count_of(c) == 0 && Heavy::alive == 1);
        }
        CHECK(Heavy::alive == 0);
    }

    // 4. self assignment, copy and move forms, must be a no-op.
    {
        CHECK(Heavy::alive == 0);
        {
            SP<Heavy> a(new Heavy("solo", 2));
#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wself-assign-overloaded"
#endif
            a = a;
#if defined(__clang__)
#pragma clang diagnostic pop
#endif
            CHECK(Heavy::alive == 1 && a->name == "solo" && count_of(a) == 1);
#if defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wself-move"
#endif
            a = std::move(a);
#if defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
            CHECK(Heavy::alive == 1 && a->name == "solo");
        }
        CHECK(Heavy::alive == 0);
    }

    // 5. deletion through a base pointer runs the derived destructor.
    {
        CHECK(Base::alive == 0);
        {
            SP<Base> p(new Derived(42));
            CHECK(Base::alive == 1 && p->tag() == 42);
            SP<Base> q = p;
            CHECK(count_of(p) == 2);
        }
        CHECK(Base::alive == 0);
    }

    // 6. weak_ptr lifecycle and lock().
    {
        CHECK(Heavy::alive == 0);
        WP<Heavy> w;
        {
            SP<Heavy> s(new Heavy("temp", 3));
            w = WP<Heavy>(s);
            CHECK(!w.expired() && Heavy::alive == 1);
            {
                SP<Heavy> locked = w.lock();
                CHECK(count_of(locked) == 2 && locked->sum() == 21);
            }
            CHECK(count_of(s) == 1);
        }
        CHECK(Heavy::alive == 0 && w.expired());
        SP<Heavy> dead = w.lock();
        CHECK(count_of(dead) == 0);
    }

    // 7. weak_ptr copy and move; the move must release the held reference, not leak it.
    {
        CHECK(Heavy::alive == 0);
        {
            SP<Heavy> s1(new Heavy("one", 1));
            SP<Heavy> s2(new Heavy("two", 1));
            WP<Heavy> wa(s1);
            WP<Heavy> wb = wa;
            CHECK(!wa.expired() && !wb.expired());
            WP<Heavy> w_held(s2);
            w_held = std::move(wa);
            CHECK(!w_held.expired());
        }
        CHECK(Heavy::alive == 0);
    }

    // 8. concurrent stress: many threads copy, destroy, and lock() the same object.
    {
        for (int iter = 0; iter < 100; ++iter)
        {
            SP<Counted> root(new Counted());
            WP<Counted> w(root);
            std::vector<std::thread> ts;
            for (int t = 0; t < 8; ++t)
            {
                ts.emplace_back([root, w]()
                                {
                    for (int i = 0; i < 300; ++i)
                    {
                        SP<Counted> local = root;
                        SP<Counted> locked = w.lock();
                        (void)local;
                        (void)locked;
                    } });
            }
            for (std::size_t i = 0; i < ts.size(); ++i)
                ts[i].join();
            CHECK(Counted::alive.load() == 1);
        }
        CHECK(Counted::alive.load() == 0);
    }

    std::cout << "ALL TESTS PASSED for " << impl << "\n";
}

int main()
{
    run_all<shared_ptr, weak_ptr>("my implementation");
    run_all<std::shared_ptr, std::weak_ptr>("std");
}